<?php

/**
 * @file
 * Implementation of plupload.module.
 */

/**
 * Implements hook_menu().
 */
function wechat_contacts_menu() {
  $items['wechat'] = array(
    'title' => 'wechat contacts',
    'description' => 'wechat contacts callback',
    'page callback' => 'wechat_contacts_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['wechat_contacts_list'] = array(
    'title' => 'wechat contacts list',
    'description' => 'wechat contacts callback',
    'page callback' => 'wechat_contacts_list',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'inc/wechat_contacts_list.inc',
  );
  $items['wechat_contacts_my_info'] = array(
    'title' => 'wechat contacts my info',
    'description' => 'wechat contacts callback',
    'page callback' => 'wechat_contacts_my_info',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'inc/wechat_contacts_my_info.inc',
  );
  $items['wechat_contacts_birth'] = array(
    'title' => 'wechat contacts birth',
    'description' => 'wechat contacts callback',
    'page callback' => 'wechat_contacts_birth',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'inc/wechat_contacts_birth.inc',
  );
  return $items;
}

function wechat_contacts_theme() {
  return array(
    'wechat_contacts_list' => array(
      'arguments' => array('title' => NULL, 'teaser' => NULL, 'link' => NULL), //
      'template' => 'hot_news',
      'file' => 'wechat_contacts_list.inc',
      'path' =>drupal_get_path('module', 'wechat_contacts'),
    ),
    'wechat_contacts_list' => array(
      'arguments' => array('title' => NULL, 'teaser' => NULL, 'link' => NULL), //
      'template' => 'hot_news',
      'file' => 'wechat_contacts_list.inc',
      'path' =>drupal_get_path('module', 'wechat_contacts'),
    ),
  );
}

function wechat_contacts_callback() {
  $we_obj = wechat_contacts_init_obj();
  $we_obj->valid();
}

function wechat_contacts_init_obj() {
  $we_obj = &drupal_static(__FUNCTION__);
  if (!isset($we_obj)) {
    module_load_include('php', 'wechat_contacts', 'sdk/qywechat.class');
    $options = array(
      'token' => variable_get('wechat_token', "hackathon"),
      'appid' => variable_get('wechat_appid', "wx2ef8799c2a79ecae"),
      'appsecret' => variable_get('wechat_appsecret', "JuB2C5V7U1jytolYZHorPxzW-U1VSIy3x4sgFFF_OuqYx-KI5jP-F2YoYgsQW06l"),
      'encodingaeskey' => '1pj2XNHL8mj8xqTQmLJafQ2Yl4tV1NPTIFXFc3MwFA2',
      
    );
    $we_obj = new Wechat($options);
  }
  return $we_obj;
}